export const reviews: Review[] = [
  {
    name: "Aarav M.",
    location: "New York, NY",
    trip: "New York to Delhi",
    rating: 5,
    text: "The whole booking process was really smooth. I got a good fare and the team was quick to respond when I had a question about my baggage allowance.",
    date: "August 2026",
    source: "Demo",
    sample: true,
  },
  {
    name: "Neha R.",
    location: "Chicago, IL",
    trip: "Chicago to Mumbai",
    rating: 5,
    text: "I was looking for a reasonable fare to Mumbai and found a great option through FlyFareDeal. The process was simple and straightforward.",
    date: "July 2026",
    source: "Demo",
    sample: true,
  },
  {
    name: "Daniel K.",
    location: "Dallas, TX",
    trip: "Dallas to Delhi",
    rating: 4,
    text: "Good experience overall. I appreciated having someone available to answer questions instead of having to figure everything out myself.",
    date: "July 2026",
    source: "Demo",
    sample: true,
  },
  {
    name: "Priya S.",
    location: "Los Angeles, CA",
    trip: "Los Angeles to Chennai",
    rating: 5,
    text: "Found a convenient flight option for my trip to Chennai. The communication was clear and the booking was handled without any hassle.",
    date: "June 2026",
    source: "Demo",
    sample: true,
  },
  {
    name: "Michael T.",
    location: "Houston, TX",
    trip: "Houston to Hyderabad",
    rating: 5,
    text: "Really liked how easy it was to compare the available options. The fare was competitive and everything was explained clearly before booking.",
    date: "June 2026",
    source: "Demo",
    sample: true,
  },
  {
    name: "Simran K.",
    location: "San Francisco, CA",
    trip: "San Francisco to Bengaluru",
    rating: 5,
    text: "Booked my trip without any unnecessary complications. The team was responsive and helped me understand the different flight options.",
    date: "May 2026",
    source: "Demo",
    sample: true,
  },
];